### PR TITLE
Update 4.3.1

### PR DESCRIPTION
**Pull request by alex-aka-axel**

### CODE REVIEW

**Review by mgoll-vmray — APPROVED** [review]

**Comment by mloebel** [comment]
We should change the `url='https://github.com/ra-kete/magic-yara-python'` in `setup.py` to also point at the right github url while we are at it

**Comment by mloebel** [comment]
I crafted this github comparision URL: https://github.com/VirusTotal/yara-python/compare/v4.3.1..vmray:magic-yara-python:update-4.3.1

All changes there should be changes only needed for the functionality provided by this fork

EDIT: Fixed the compare to compare the right things and in the right direction

**Comment by mloebel** [comment]
Okay now that I looked at the right diff, the only unexpected diff to me seems to be that our fork enables this line:
```py
module.define_macros.append(('HAVE_STDBOOL_H', '1'))
```
here: https://github.com/VirusTotal/yara-python/compare/v4.3.1..vmray:magic-yara-python:update-4.3.1#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R207

**Review by mloebel — APPROVED** [review]

**Comment by mloebel** [comment]
> Okay now that I looked at the right diff, the only unexpected diff to me seems to be that our fork enables this line:
> 
> ```python
> module.define_macros.append(('HAVE_STDBOOL_H', '1'))
> ```
> 
> here: https://github.com/VirusTotal/yara-python/compare/v4.3.1..vmray:magic-yara-python:update-4.3.1#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R207

This was introduced in https://github.com/vmray/magic-yara-python/commit/c5cc07335e685034c7b2d874c379e51c25473f12, which seems fine to keep

**Pull request merged**
